platform :ios, '14.0'
source 'https://cdn.cocoapods.org/'
use_frameworks!
inhibit_all_warnings!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'SampleApp' do
	inherit! :search_paths

	pod 'Playbook', '~> 0.2.0'
end

target 'SampleAccessibilitySnapshot' do
	inherit! :search_paths

	pod 'PlaybookAccessibilitySnapshot', :path => '../PlaybookAccessibilitySnapshot.podspec'
end
