use_frameworks!
use_modular_headers!
platform :ios, '13.0'
source 'https://cdn.cocoapods.org/'

target 'SampleAccessibilitySnapshot' do
	inherit! :search_paths

	pod 'AccessibilitySnapshot/Core'
	pod 'Playbook', :git => 'https://github.com/jiayi-zhou/playbook-ios', :branch => 'accessibility-support'
	pod 'PlaybookAccessibility', :path => '../PlaybookAccessibility.podspec'
end

install! 'cocoapods', :disable_input_output_paths => true
