name: Example
options:
  createIntermediateGroups: true
  bundleIdPrefix: app.playbook-ui.accessibility.Example
  deploymentTarget:
    iOS: 14.0

settings:
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_IDENTITY: "-"
  CODE_SIGN_STYLE: Manual

packages:
  PlaybookAccessibilitySnapshot:
    path: ..

targets:
  SampleApp:
    Example:
    type: application
    platform: iOS
    sources: SampleApp
    scheme:
      testTargets:
        - SampleAccessibilitySnapshot
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/Snapshots

  SampleAccessibilitySnapshot:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SampleAccessibilitySnapshot
    dependencies:
      - target: SampleApp
      - package: PlaybookAccessibilitySnapshot
