name: Example
options:
  bundleIdPrefix: app.playbook-ui.accessibility.Example
  deploymentTarget:
    iOS: 14.2

packages:
  PlaybookAccessibilitySnapshot:
    path: ..

targets:
  SampleApp:
    Example:
    type: application
    platform: iOS
    sources: SampleApp
    scheme:
      testTargets:
        - SampleAccessibilitySnapshot
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/Snapshots
    attributes:
      ProvisioningStyle: Manual

  SampleAccessibilitySnapshot:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SampleAccessibilitySnapshot
    dependencies:
      - target: SampleApp
      - package: PlaybookAccessibilitySnapshot
    attributes:
      ProvisioningStyle: Manual
