format:
  indent: 4
  lineBreakBeforeEachArgument: true

targets:
  main:
    paths:
      - Sources
      - Example/SampleApp
      - Example/SampleAccessibilitySnapshot
    rules:
      defaultAccessLevel:
        accessLevel: openOrPublic
        implicitInternal: true

      defaultMemberwiseInitializer:
        implicitInitializer: true
        implicitInternal: true
        ignoreClassesWithInheritance: true
