name: PlaybookAccessibility
options:
  bundleIdPrefix: app.playbook-ui-accessibility
  createIntermediateGroups: true
  postGenCommand: pod install

schemes:
  PlaybookAccessibility:
    build:
      targets:
        PlaybookAccessibility: all
    test:
      targets:
        - PlaybookAccessibility-Tests
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        ACC_SNAPSHOT_DIR: $(SOURCE_ROOT)/AccessibilitySnapshots
        
packages:
    Playbook:
        path: ~/playbook-ios

targets:
  PlaybookAccessibility:
    type: framework
    platform: iOS
    sources:
      - Sources/PlaybookAccessibility
    configFiles:
      Debug: XCConfigs/playbook-accessibility.xcconfig
      Release: XCConfigs/playbook-accessibility.xcconfig
    dependencies:
      - package: Playbook
        product: PlaybookUI
      
  PlaybookAccessibility-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: PlaybookAccessibility
